### ISSUE TITLE
有应用场景吗？

### ISSUE THREAD

**Issue by azkoss** [EliMirren/VX-API-Gateway#1]

**Comment by shenzhenMirren** [comment]
理论上任何应用场景都合适,最合适的就是作为前后端分离API的使用,截止到今天我们自己公司已经在线上生产17天了,效果挺理想的,1.0.2版支持body的透传就可以支持文件上传相关

**Comment by azkoss** [comment]
并发测试的效果怎么样？测试用例是不是还没有？

**Comment by shenzhenMirren** [comment]
vert.x单核理论上1秒可以1万以上的QPS,每个人的应用环境不同,一切还是自己测试了就知道什么效果
这是我们2C4g10带宽的centos7的测试结果
![webtest](https://user-images.githubusercontent.com/24805209/40044458-fc1624f0-5859-11e8-9f9a-e7c7b61a1c65.png)

**Comment by shenzhenMirren** [comment]
上面的测试是在没有调整Xms,Xmx参数的测试结果,如果调整了减少了GC的次数的话效果更好
