### ISSUE TITLE
多个应用使用相同端口时会出现问题

### ISSUE THREAD

**Issue by onemy** [EliMirren/VX-API-Gateway#7]
如题，程序中允许多应用使用同一端口，但会出现服务not found resource的错误，时好时坏，更换端口后正常，不知是什么原因

**Comment by shenzhenMirren** [comment]
多应用使用一个端口,如果应用暂停或重启后就会出现这种情况,目前的解决方式就是重启整个网关就不会,这边已经在计划做新版本,新版本会采用接口分组的模式,然后应用也会优化,性能就会有很大的提升
